### ISSUE TITLE
aframe-text-component doesn't work with aframe 4.0

### ISSUE THREAD

**Issue by giordyb** [ngokevin/aframe-text-component#20]
Hi,

When using this component with aframe 4.0 the page doesn't show the scene and in the console I get the following error:
```
Uncaught (in promise) TypeError: paths[p].toShapes is not a function
    at Object.THREE.FontUtils.generateShapes (aframe-text-component.js:350)
    at new THREE.TextGeometry (aframe-text-component.js:410)
    at getTextGeometry (aframe-text-component.js:78)
    at i.update (aframe-text-component.js:73)
    at i.updateProperties (component.js:209)
    at i.module.exports.Component (component.js:35)
    at new i (component.js:277)
    at HTMLElement.value (a-entity.js:362)
    at HTMLElement.value (a-entity.js:513)
    at e (a-entity.js:486)
```

this is just with a simple html like this

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>text-component</title>
    <meta name="description" content="text-component">
   
    <script src="https://aframe.io/releases/0.4.0/aframe.min.js" > </script> 
     <script src="https://rawgit.com/ngokevin/aframe-text-component/master/dist/aframe-text-component.js" ></script>
    </head>
<body>

     <a-scene>
    <a-entity text="text: What's up"></a-entity>
  </a-scene>
</body>
</html>
```

**Comment by ngokevin** [comment]
The repo has been moved to kframe, but will fix thanks
